# Generated by Django 2.2.4 on 2019-08-05 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchid', models.CharField(blank=True, max_length=13, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('tyear', models.CharField(blank=True, max_length=3, null=True)),
                ('tpart', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departmentid', models.CharField(blank=True, max_length=2, primary_key=True, serialize=False)),
                ('departmentname', models.CharField(blank=True, max_length=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupid', models.CharField(blank=True, max_length=13, primary_key=True, serialize=False)),
                ('noofstudents', models.IntegerField(blank=True, null=True)),
                ('complementary_group', models.CharField(blank=True, max_length=3, null=True)),
                ('batchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('programid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('programname', models.CharField(blank=True, max_length=32, null=True)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectid', models.CharField(blank=True, max_length=13, primary_key=True, serialize=False)),
                ('subjectname', models.CharField(blank=True, max_length=50, null=True)),
                ('tyear', models.CharField(blank=True, max_length=3, null=True)),
                ('tpart', models.CharField(blank=True, max_length=2, null=True)),
                ('iselective', models.BooleanField(blank=True, null=True)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherid', models.CharField(blank=True, max_length=3, primary_key=True, serialize=False)),
                ('teachername', models.CharField(blank=True, max_length=32, null=True)),
                ('totalclasses', models.IntegerField(blank=True, null=True)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('timeid', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('alternation', models.BooleanField(blank=True, null=True)),
                ('classes', models.CharField(blank=True, max_length=11, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUES', 'Junior'), ('WED', 'Senior'), ('THURS', 'Thursday'), ('FRI', 'Friday')], default='SUN', max_length=3)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Groups')),
                ('programid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Programs')),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subjects')),
                ('teacherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomname', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=40, null=True)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Departments')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='programid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Programs'),
        ),
    ]
