# Generated by Django 2.2.4 on 2019-08-02 13:30

from django.db import migrations

def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(first_name="Customer 001", last_name="Customer 001", email="customer001@email.com", phone="00000000", address="Customer 000 Address", description= "Customer 001 description").save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(create_data),
        migrations.RemoveField(
            model_name='customer',
            name='createdAt',
        ),
    ]
